spring.application.name=scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/tasktracker_db
spring.datasource.username=tasktracker
spring.datasource.password=tasktracker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer